allowBuilds:
  esbuild: true
  sharp: true

blockExoticSubdeps: true

engineStrict: true

minimumReleaseAge: 4320 # 3 days

strictDepBuilds: true

strictPeerDependencies: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 43200 # 30 days
